### PR TITLE
Support empty string, null and falsy values as key for GroupBy

### PR DESCRIPTION
**Pull request by barakbbn**
Avoid filtering out falsy keys/values ('', null, 0, false) in
`lib/utilities.ts`

```ts
function getKeyedMap()
function getKeyedMapFast()
function getKeys()```

### CODE REVIEW

**Comment by ENikS** [comment]
Looks like there are some missing cases in your tests?

**Comment by barakbbn** [comment]
1. Regarding the test coverage, it seems false alarm since
in previous builds it was the same but somehow the coverage percentage become less accurate.
I went through the coverage and previous one and they exactly the same.
**I did notice though,**
that in lib/linq.ts  `OrderedLinq.ThenByDescending` 
doesn't have coverage (also in older builds) for line inside if statement
```ts
if (!this.comparer) {
    this.comparer = compare;
} else {
```
i.e. in sibling method `ThenBy` same condition is covered.
I couldn't figure out why, so your handling is needed here

2. I will also commit code adjustment the behavior of `Join`, `GroupJoin` to handle null key like C#
in which Join ignores null key, but GroupJoin supports it

Thanks

**Comment by barakbbn** [comment]
I investigate a little the `ThenBy`, `ThenByDescending` functionality.
It seems they behavior a ltitle differently than in C#.
in C# they are immutable, meaning a code such as
```ts
const base = items.OrderBy(x => x.name);
const asc  = base.ThenBy(x => x.grade);
const desc = base.ThenByDescending(x => x.age);
```
works in C# but here it doesn't, since here `ThenBy` , `ThenByDescending` are mutable and change `this` and `return this`
so `desc` affects `asc` in the above example

What do you think?

if you think it's worth fixing, I can open an issue and make the necessary changes

thanks

**Comment by ENikS** [comment]
I would really appreciate that! I am working on next version of [Unity Container](https://github.com/unitycontainer) and can't spend much time on this library at the moment.

**Pull request merged**
